### ISSUE TITLE
Why I have different number of passing tests from NUnit Console Runner than Ghpr Reporter?

### ISSUE THREAD

**Issue by MichalSle** [GHPReporter/Ghpr.SpecFlow#18]
Hello,
I came across another number of tests in NUnit Console Runner (3.7.0) than Ghpr Reporter
From NUnit Console Runner I have this summary:
Overall result: Failed
20:54:40   Test Count: 59, Passed: 33, Failed: 8, Warnings: 0, Inconclusive: 12, Skipped: 6
20:54:40     Failed Tests - Failures: 1, Errors: 7, Invalid: 0
20:54:40     Skipped Tests - Ignored: 6, Explicit: 0, Other: 0
In Ghpr Reporter
Total: 53
Success: 51
Errors: 1
Failures: 1
Inconclusive: 0
Ignored: 0
Unknown: 0

My tests are using SpecFlow in Parallel. Maybe should I tried with property realTimeGeneration false/true. It didn't help.
Do you know any solution for this?

**Comment by elv1s42** [comment]
Hi @MichalSle !

The reason is in the way we read test results from SpecFlowPlugin.
I'll make some changes to NUnit Specflow Plugin, so we will take test result from NUnit test context.

Thank you for submitting this issue!

**Comment by MichalSle** [comment]
Awesome. Thank you!

**Comment by elv1s42** [comment]
Hi, this was released
