### ISSUE TITLE
Clearly difference in time between tests with report than test without report

### ISSUE THREAD

**Issue by MichalSle** [GHPReporter/Ghpr.SpecFlow#19]
Hi,
I saw clearly the difference between use tests without report than tests with the report. It's approximately 2 or 3 times longer time than normal. Ofc, it's also the reason because I use screenshots, however, is quite long time. I'm using Ghpr report on parallel mode.
Do you know any idea how to increase the speed of it? Maybe Ghpr report should have option turn on and turn off? or should it maybe create after did test-results.xml ?
I'd very like your report. In my opinion is the best from available reports. 
Cheers,
Michał

**Comment by elv1s42** [comment]
Hi @MichalSle !

If your tests are running quickly without using Ghpr then you can try to generate the report after your test run is finished. 

At the moment you can do it for MSTest tests by converting .trx test result file using Ghpr.MSTest.

For SpecFlow tests you still can get .trx test result file, but only if you are using MSTest as unit test provider:
![image](https://user-images.githubusercontent.com/6689884/31005823-012db6de-a503-11e7-887b-753bd266c388.png)

For NUnit tests I think we can create console application for converting existing .xml test result file into the report.

Also you can try to turn off real-time report generation by setting realTimeGeneration = "False", see https://github.com/GHPReporter/Ghpr.Core#about-settings-file


Thank you.

**Comment by MichalSle** [comment]
Hi @elv1s42 
Thank you for your fast respond 👍 
Yes. I don't mention that I use NUnit. I would be very grateful if you create a console application for converting existing .xml test result file into the report.
I had put "False" realTimeGeneration however, it's not a big difference.

**Comment by elv1s42** [comment]
@MichalSle , so you are using NUnit as unitTestProvider for SpecFlow tests, correct?

**Comment by MichalSle** [comment]
Yes. I'm using NUnit for SpecFlow tests which are e2e tests with selenium.  After running tests, I receive existing .xml file. Also, I use Ghpr report as tag such as  <add name="Ghpr.NUnit" type="Runtime" />

**Comment by elv1s42** [comment]
Ok, @MichalSle you can also try another option. 
As far as SpecFlow tests based on NUnit are NUnit tests, you can try to run all these tests with NUnit Console with turning off real-time generation. 

You can see some details here: https://github.com/GHPReporter/Ghpr.NUnit#usage

For this issue I'll create a new one in Ghpr.Nunit repository with **enhancement** label and implement ability to generate the report from NUnit .xml results.

**Comment by MichalSle** [comment]
@elv1s42  thank you!
I'll wait for it!

**Comment by elv1s42** [comment]
Created https://github.com/GHPReporter/Ghpr.NUnit/issues/27

If you have some time, please try using NUnit Console with Ghpr.NUnit (and with turning off real-time generation). I think this may speed up report generation.

**Comment by elv1s42** [comment]
Closing this issue, because another one is created in Ghpr.NUnit repository
