### ISSUE TITLE
Screenshots or specflow output missing

### ISSUE THREAD

**Issue by AdrianSTANCULESCU** [GHPReporter/Ghpr.SpecFlow#20]
Hi,
I have the following issue:
For tests that fail I make a screenshot and in GHPReporter if I have values for output screenshots are missing and if I have screenshots the test output is missing.
I think is something related with ,json files, but I'm not sure.
I've putted in json files only one path: C:\\_GHPReporter_NUnit_Report and also put this path in nunit add-on.
I'm running report from nunit console. The screenshot is saved but is not displayed in browser. I don't know the source of test outputs.
Any suggestions please?
Thank you,

Adrian.

**Comment by elv1s42** [comment]
Hi @AdrianSTANCULESCU ,

Are you taking screenshot after test is finished (in [AfterScenario] for example)?
In this case screenshot may not appear in the report.

What unitTestProvider are you using, MSTest or NUnit? 

Thank you

**Comment by AdrianSTANCULESCU** [comment]
Hi,
Yes, I'm using nunit, I take screenshots in [AfterScenario].
I want conditions the screenshot may appear?
Thanks!

**Comment by elv1s42** [comment]
Hi @AdrianSTANCULESCU !

You can use something like this:
![image](https://user-images.githubusercontent.com/6689884/34557545-aa19ce06-f14b-11e7-8090-a31283024856.png)

I've tested that case and sceenshot was inserted in the report correctly

Thank you

**Comment by AdrianSTANCULESCU** [comment]
Hi elv1s42,
You're right, it generates me the screenshot, but in some cases with different name, so I think is not mapped with folder name.
For example: file:///C:/_GHPReporter_SpecFlow_Report/tests/index.html?testGuid=192c61b1-2de5-2c41-d5fe-61b892968d12&testFile=test_20171221_133935066.json&currentTab=test-output

When I'm getting the screenshot I have empty data in Test output tab.
I think it's something misconfigured.
What type of log data can help you?

Thanks.

**Comment by elv1s42** [comment]
Hi @AdrianSTANCULESCU , yes, some examples would be helpful.
I need some example to debug the plugin.
Also can you please check if the screenshot exist in corresponding test's .json file?
![image](https://user-images.githubusercontent.com/6689884/34714401-67ad95c8-f53a-11e7-9182-611dfbb56ed4.png)


Thank you

**Comment by AdrianSTANCULESCU** [comment]
Hi Elvis,

Sorry for late response: O've checked the json test file, but my screenshot array is empty.
I've also modified the AfterScenario condition to be exactly as you described above.

Thanks.

**Comment by elv1s42** [comment]
Hi @AdrianSTANCULESCU 

In that case I need some more details about the test. Are you able to create a simple example which will reproduce the issue? I still wasn't able to reproduce it

Thank you
