### ISSUE TITLE
[Feature] Support SpecFlow 3

### ISSUE THREAD

**Issue by elv1s42** [GHPReporter/Ghpr.SpecFlow#47]
Support for the new package version

**Comment by yfrindel** [comment]
Hi Evgeniy ! how are you since the last time ? ;)
Do you know when Ghpr.specflow will be ready for specflow 3 please ?
Regards
Yannick

**Comment by elv1s42** [comment]
Hi @yfrindel !
This is going to be released this week, but please be aware that there is no proper testing done for .NET Core.

**Comment by elv1s42** [comment]
This one was released yesterday.
@yfrindel, I didn't have much time to test all possible cases, so please feel free to raise any bugs as a separate issues under this repository.
